generator:
  working_point:
    snr_db: 10.0
    freq_sep: 0.03
    eig_mag: 0.96
    eig_mag_spread: 0.0
    delays_over_timesteps: 0.33
    spatial_dim: 30
    temporal_dim: 200
    top_amplitude: 1.0
    num_modes: 2
    max_rank: 14
    artificial_damping: 1.0

parameters:
  snr_db:
    type: range
    role: wp
    start: -5
    end: 20
    num_steps: 26
    scale: lin              # or "log"

  freq_sep:
    type: range
    role: wp
    start: 0.003
    end: 0.5
    num_steps: 20
    scale: log

  eig_mag:
    type: range
    role: wp
    start: 0.9
    end: 1.0
    num_steps: 20
    scale: lin

  eig_mag_spread:
    type: range
    role: wp
    start: 0.001
    end: 0.05
    num_steps: 10

  delays_over_timesteps:
    type: range
    role: wp
    start: 0.025
    end: 0.525
    num_steps: 11

  spatial_dim:
    type: range
    role: wp
    start: 10
    end: 50
    num_steps: 10
    as_int: true

  temporal_dim:
    type: range
    role: wp
    start: 80
    end: 530
    num_steps: 10
    as_int: true

  top_amplitude:
    type: range
    role: wp
    start: 1.0
    end: 3.0
    num_steps: 20
    scale: lin

  artificial_damping:
    type: range
    role: wp
    start: 0.92
    end: 1.0
    num_steps: 9
    scale: lin

  num_modes:
    type: range
    role: wp
    start: 2
    end: 6
    num_steps: 5

  max_rank:
    type: range
    role: wp
    start: 8
    end: 38
    num_steps: 11

  noise_mode:
    type: list
    role: cartesian
    values: ["gaussian", "bi_gaussian","uniform", "student_t", "hetero", "ar1"]

# Any other args your run_on_conf needs that are constant:
static_args:
  n_iter:    500
  dt:        1.0
  rho_mode: random
  random_seed: null
  cluster_algorithm: gmm

# === PBS & paths & outputs ===
pbs:
  queue: zeus_comb_short
  mem:   1000MB
  ncpus: 1
  mpiprocs: 1
  walltime: "02:30:00"

paths:
  interpreter: /home/yoav.h/miniconda/envs/zeus-dmd/bin/python3.11
  code_dir:    /home/yoav.h/dmd-proj/mode-structure-dmd-order-detection
  exp_script:  run_on_conf.py

output:
  output_dir: 'out_dir'
