project_root: "../../.."

plotting:
  mplstyle_path: "figures/mplstyle_files/chaos_single.mplstyle"
  
  rsln:
    version: "perturbed"  # "clean" | "perturbed"

  figure:
    type: "boxplot"
    annotate_gap_panel: 0
    show_titles: false
    # panel_height: 2.4  # Optional override  

  scenarios:
    - name: "easy"
      label: "Easy"
      csv_path: 'C:\Users\Yoav\PycharmProjects\dc-dmd-order-detection\figures\leakage\data\leakage_results_easy.csv'

output:
  output_dir: "figures/leakage/outputs"
#  filename: "leakage_main_text.png"
  filename: "leakage_main_text1000.png"

